
// falta ponerle un alert y quitarle la x de la ventana ****************

/*
 * AbrirRemMissing.java
 *
 * Created on 20 de mayo de 2006, 06:11 PM
 */

package gui.Icons.Filters.NumericRange;

import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author  Tariy
 */
public class AbrirRangNumer extends javax.swing.JFrame {
    AbstractTableModel datosEntrada;
    String atributos[];
    int colsel, pa, minval, maxval;
    /** Creates new form AbrirRemMissing */
    public AbrirRangNumer(AbstractTableModel dataIn) {
        datosEntrada = dataIn;
        atributos  = new String[datosEntrada.getColumnCount()+1];
        pa = 1;
        atributos[0] = "Seleccionar un Atributo";
        for(int i = 0; i < datosEntrada.getColumnCount(); i++) {
            if(datosEntrada.getColumnClass(i).getSimpleName().equals("Integer")) {
                atributos[pa] = datosEntrada.getColumnName(i);
                pa ++;
            }
        }
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        BtnAplicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CmbAtributos = new javax.swing.JComboBox();
        BtnReset = new javax.swing.JButton();
        BtnCerrar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        TxtMinVal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtMaxVal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Abrir Rango Numerico");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        jPanel1.setBackground(new java.awt.Color(81, 81, 133));
        BtnAplicar.setText("Aplicar");
        BtnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAplicarActionPerformed(evt);
            }
        });
        BtnAplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAplicarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atributo    :");

        CmbAtributos.setFont(new java.awt.Font("Tahoma", 0, 12));
        CmbAtributos.setModel(new javax.swing.DefaultComboBoxModel(atributos));

        BtnReset.setText("Resetear");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResetMouseClicked(evt);
            }
        });

        BtnCerrar.setText("Cerrar");
        BtnCerrar.setEnabled(false);
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remplazar el rango con valores nulos ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(185, 220, 255)));
        TxtMinVal.setFont(new java.awt.Font("Tahoma", 0, 12));
        TxtMinVal.setBounds(40, 60, 90, 50);
        jLayeredPane1.add(TxtMinVal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Minimo Valor");
        jLabel2.setBounds(40, 30, 90, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Maximo Valor");
        jLabel3.setBounds(190, 30, 100, 17);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TxtMaxVal.setFont(new java.awt.Font("Tahoma", 0, 12));
        TxtMaxVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtMaxValActionPerformed(evt);
            }
        });

        TxtMaxVal.setBounds(190, 60, 90, 50);
        jLayeredPane1.add(TxtMaxVal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                        .add(CmbAtributos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 321, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(BtnAplicar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                        .add(BtnReset, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(29, 29, 29)
                        .add(BtnCerrar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(CmbAtributos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(BtnCerrar)
                    .add(BtnAplicar)
                    .add(BtnReset))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 262, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void TxtMaxValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtMaxValActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_TxtMaxValActionPerformed
    
    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        CmbAtributos.setModel(new javax.swing.DefaultComboBoxModel(atributos));
        TxtMaxVal.setText("");
        TxtMinVal.setText("");
    }//GEN-LAST:event_BtnResetActionPerformed
    
    private void BtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseClicked
        
    }//GEN-LAST:event_BtnResetMouseClicked
    
    private void BtnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAplicarActionPerformed
        String cad;
        char uc;
        int x=0, bdmin = 0, bdmax = 0;
        //------------------------
        colsel = datosEntrada.findColumn(CmbAtributos.getModel().getSelectedItem().toString());
        if(colsel == -1){
            TxtMaxVal.setText("");
            TxtMinVal.setText("");
            JOptionPane.showMessageDialog(this, "Debe seleccionar algun Atributo",
                    "Error en Abrir Rango Numerico",JOptionPane.ERROR_MESSAGE);
        } else {
            x=0;
            cad = TxtMinVal.getText();
            for(int y = 0; y < cad.length(); y++) {
                uc = cad.charAt(y);
                if(uc>47 && uc<58) x++;
            }
            if(x==cad.length()) {
                bdmin = 1;
            } else {
                JOptionPane.showMessageDialog(this, "Minimo Valor debe ser Numerico",
                        "Error en Abrir Rango Numerico",JOptionPane.ERROR_MESSAGE);
                bdmin = 0;
            }
            
            x=0;
            cad = TxtMaxVal.getText();
            for(int y = 0; y < cad.length(); y++) {
                uc = cad.charAt(y);
                if(uc>47 && uc<58) x++;
            }
            if(x==cad.length()) {
                bdmax = 1;
            } else {
                JOptionPane.showMessageDialog(this, "Maximo Valor debe ser Numerico",
                        "Error en Abrir Rango Numerico",JOptionPane.ERROR_MESSAGE);
                bdmax = 0;
            }
        }
        if(bdmin == bdmax && bdmax == 1) {
            minval = Integer.parseInt(TxtMinVal.getText());
            maxval = Integer.parseInt(TxtMaxVal.getText());
            if(minval < maxval) {
                BtnCerrar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "Minimo Valor debe ser menor que Maximo Valor",
                        "Error en Abrir Rango Numerico",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnAplicarActionPerformed
    
    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        //System.exit( 0 );
        dispose();
    }//GEN-LAST:event_BtnCerrarActionPerformed
    
    private void BtnAplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAplicarMouseClicked
        
    }//GEN-LAST:event_BtnAplicarMouseClicked
    
    public int getColSelec() {
        return colsel;
    }
    
    public int getMaxVal() {
        return maxval;
    }
    
    public int getMinVal() {
        return minval;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AbrirRangNumer().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAplicar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox CmbAtributos;
    private javax.swing.JTextField TxtMaxVal;
    private javax.swing.JTextField TxtMinVal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
