/*
 * showRules.java
 *
 * Created on 31 de mayo de 2006, 21:55
 */

package gui.Icons.Rules;

import Utils.AssocRules;
import Utils.ExampleFileFilter;
import Utils.FileManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author  ivan
 */
public class showRules extends javax.swing.JFrame {
    /** Las reglas de asociaciÃ³n. */
    private AssocRules rules;
    
    /** Tabla analizada. */
    private String table;
    
    /** Soporte minimo del sistema. */
    private String support;
    
    /** Confianza. */
    private String confidence;
    
    /** Creates new form ShowRules */
    public showRules(AssocRules rules, String table, String support, String confidence) {
        this.rules = rules;
        this.table = table;
        this.support = support;
        this.confidence = confidence;
        
        initComponents();
        
        if(rules.getRules().size() != 0) {
            RulesTableModel model = new RulesTableModel(rules.getRules());
            tblRules.setModel(model);

//            columnSizes();
        } else {
            // No hay resultados //
        }
        
        lblTable.setText(table);
        lblSupport.setText(support + "%");
        lblConfidence.setText(confidence + "%");
        
        this.addJTableHeaderListener();
    }
    
    public void addJTableHeaderListener() {
        MouseAdapter mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                TableColumnModel columnModel = tblRules.getColumnModel();
                int viewColumn = columnModel.getColumnIndexAtX(e.getX());
                //System.out.println("column model " + viewColumn);
                int column = tblRules.convertColumnIndexToModel(viewColumn);
                System.out.println("column " + column);
                // Ordenar elementos de la columna de la tabla.
                if(e.getClickCount() == 1 && column != -1) {
                    // Ordenar por confianza.
                    if(column == 1) {
                        rules.sortByGoldStone(0);
                        rules.sortByGoldStone(1);
                        RulesTableModel rtm = new RulesTableModel(rules.getRules());
                        tblRules.setModel(rtm);
                    } else if(column == 2) {
                        RulesTableModel rtm = new RulesTableModel(rules.sortByConfidence());
                        tblRules.setModel(rtm);
                    }
                }
            }
        };
        JTableHeader header = tblRules.getTableHeader();
        header.addMouseListener(mouseListener);
    }
    
//    public void columnSizes() {
//        int columns = model.getColumnCount();
//        int csize = 0;
//        TableColumn column = null;
//        
//        for (int i=0; i<columns; i++) {
//            column = tblRules.getColumnModel().getColumn(i);
//            csize = model.getColumnName(i).length();
//            column.setPreferredWidth(csize*10);
//        }
//    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        Save = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        lblTable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSupport = new javax.swing.JLabel();
        lblConfidence = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRules = new javax.swing.JTable();

        Save.setCurrentDirectory(new java.io.File("/home/ivan/tariy/Reportes"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock_text_justify.png")));
        jLabel1.setText("Analized Table:");

        lblTable.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        lblTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(163, 184, 204), 1, true));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/text_strike.png")));
        jLabel2.setText("System Support:");

        lblSupport.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        lblSupport.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(163, 184, 204), 1, true));

        lblConfidence.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        lblConfidence.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(163, 184, 204), 1, true));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rules.png")));
        jLabel3.setText("Confidence:");

        btn_atras.setIcon(new javax.swing.ImageIcon("/usr/share/icons/Bluecurve/20x20/actions/back.png"));
        btn_atras.setText("Back");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon("/usr/share/icons/crystalsvg/22x22/actions/save_all.png"));
        btnSave.setText("Save Report");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblRules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRules);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .add(16, 16, 16)
                        .add(lblTable, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(29, 29, 29)
                                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(15, 15, 15)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblSupport, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblConfidence, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(btn_atras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .add(448, 448, 448)
                        .add(btnSave, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                        .add(5, 5, 5)))
                .add(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(lblSupport, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblConfidence, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(33, 33, 33)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_atras)
                    .add(btnSave))
                .add(36, 36, 36))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
    }//GEN-LAST:event_formMousePressed
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
// TODO add your handling code here:
        ExampleFileFilter ext = new ExampleFileFilter(".tux", "Archivo de reglas");
        String path;
        FileManager fm;
        
        Save.addChoosableFileFilter(ext);
        int saveOK = Save.showSaveDialog(this);
        if(saveOK == Save.APPROVE_OPTION) {
            path = Save.getSelectedFile().getAbsolutePath();
            path += ".tux";
            fm = new FileManager(path);
            fm.writeString("ASSOCIATION RULES\n\nMined with: " + table + "\n" +
                    "Support: " + support + "%\n" + "Confidence: " + confidence +
                    "%\n\n" + rules.toString());
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_atrasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new showRules().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser Save;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btn_atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConfidence;
    private javax.swing.JLabel lblSupport;
    private javax.swing.JLabel lblTable;
    private javax.swing.JTable tblRules;
    // End of variables declaration//GEN-END:variables
    
}
